### ISSUE TITLE
Prepare login view

### ISSUE THREAD

**Issue by songofroland** [wilmhit/easyWarehouse#2]
Staff should have possibility to login and start work. That being said, a [login view](https://docs.djangoproject.com/en/3.1/topics/auth/default/#how-to-log-a-user-in) must be implemented. The following requirements describe completed task:

- [x] User is able to login via the login view
- [x] The login view is properly tested (a unit test is present)

**Comment by wilmhit** [comment]
+1 for how descriptive this task is. You even troubled yourself with a link.
